= Final Project
P치szti Tibor Mikl칩s & P칩ra D치vid
include::utils.adoc[]

== Introduction

In this project we documented the network infrastructure 
of a package delivery company. Like https://gls-group.com/HU/hu/home/[GLS]
and https://www.foxpost.hu/[FOXPOST], this company delivers to 
package lockers.

There are three sites:

Headquarters:: This location is where the company handles acounting and development.
Office:: This location offers in person customer service and package pick up.
Package Center:: This location houses the packages and the company servers.

<<<

== Project Management

=== Task Tracking
The task are tracked using https://trello.com/[Trello] with 
each task being assigned to one of three lists.

- *Todo*
- *In Progress*
- *Done*

The task naming convention is: *<category>: <topic>*

==== Automations

===== Labeling

Automations are set up to assign colored labels depending
on the category at the start of the task name. 
These categories are:

- *Documentation*
- *Network*
- *Linux server*
- *Windows server*

When a task is dragged into the Done list the Done label
is automatically assigned.

===== miscellaneous

There is an automation that when dragging a task 
from Todo to In Progress, it automatically assigns the
said person to the task.


=== Documentation
The documentation is written in https://asciidoctor.org/[Asciidoctor]
and converted into PDF. This document is stored on https://github.com/[Github]
for easier teamwork and version control.

Every addition to the documentation is a new branch that has the 
following naming convention:

- *Networking:* network/<site>/<topic>
- *Server:* server/<OS>/<topic>
- *Documentation:* docs/<topic>

When an addition is completed the person assigned to the task has to issue
a pull-request and the other party has to authorize it.
